---
- name: Practica de Ansible con Docker
  hosts: docker
  gather_facts: yes  # Esto le dice a Ansible que recolecte datos del sistema (Facts)

  tasks:
    - name: Mostrar el nombre del host
      debug:
        msg: "El nombre del host es: {{ ansible_hostname }}"

    - name: Mostrar el sistema operativo
      debug:
        msg: "El sistema operativo es: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Crear el directorio /tmp/ansible-demo
      file:
        path: /tmp/ansible-demo
        state: directory
        mode: '0755'

    - name: Crear un archivo info.txt con datos del sistema
      copy:
        dest: /tmp/ansible-demo/info.txt
        content: |
          Nombre del Servidor: {{ ansible_hostname }}
          Sistema Operativo: {{ ansible_distribution }}
        mode: '0644'

    - name: Crear directorios mediante un loop
      file:
        path: "/tmp/ansible-demo/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - logs
        - backup
        - config

    - name: Mostrar un mensaje unicamente si el sistema operativo es Ubuntu
      debug:
        msg: "Confirmado: Este sistema operativo es Ubuntu."
      when: ansible_distribution == "Ubuntu"